# Generated by Django 6.1 on 2026-09-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
